// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperStockpileMan.Bus.Contexts;

#nullable disable

namespace SuperStockpileMan.Bus.Migrations
{
    [DbContext(typeof(SuperStockpileManContext))]
    [Migration("20260719063149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.CategoryBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("CategoryBases");

                    b.HasDiscriminator().HasValue("CategoryBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmallestCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SmallestCategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.Category", b =>
                {
                    b.HasBaseType("SuperStockpileMan.Bus.Models.CategoryBase");

                    b.HasDiscriminator().HasValue("Category");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.SmallestCategory", b =>
                {
                    b.HasBaseType("SuperStockpileMan.Bus.Models.CategoryBase");

                    b.HasDiscriminator().HasValue("SmallestCategory");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.CategoryBase", b =>
                {
                    b.HasOne("SuperStockpileMan.Bus.Models.Category", null)
                        .WithMany("Children")
                        .HasForeignKey("CategoryId");

                    b.HasOne("SuperStockpileMan.Bus.Models.CategoryBase", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.Item", b =>
                {
                    b.HasOne("SuperStockpileMan.Bus.Models.Location", "Location")
                        .WithMany("Items")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperStockpileMan.Bus.Models.SmallestCategory", "SmallestCategory")
                        .WithMany("Items")
                        .HasForeignKey("SmallestCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("SmallestCategory");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.Location", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("SuperStockpileMan.Bus.Models.SmallestCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
